title:        Portfolio
tagline:      'Tomoya Ikeda'
description:  'ポートフォリオ用のサイトを作ってみた'
url:          https://motacapla.github.io/
version:      1.1.1
author:
  name:       'tomoya ikeda'
  email:      't.i.motacapla[at]gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
